version: '3'

services:
  map:
    image: overv/openstreetmap-tile-server
    volumes:
      - osm-data:/data/database/
    ports:
      - "8080:80"
    command: "run"

volumes:
  osm-data:
    external: true
