version: '3'

services:
  map:
    image: openstreetmap-tile-server-can
    volumes:
      - osm-data:/data/database/
    ports:
      - "8080:80"
    command: "run"

volumes:
  osm-data:
    external: true
